### ISSUE TITLE
chia-monitor setup in a secondary network reports a duplicate harvester

### ISSUE THREAD

**Issue by charnet3d** [philippnormann/chia-monitor#24]
* Configuration:

So I have a peculiar setup with 2 chia full nodes in different locations, each with its harvesters, and I wanted to set them up in a single dashboard, because all the plots are for the same wallet.

```
Node A - Harvester A1 (127.0.0.1)
Harvester A2 (192.168.1.200)

Node B - Harvester B1 (127.0.0.1)
Harvester B2 (192.168.2.205)
Harvester B3 (192.168.2.8)
```
(The IP adresses are the same ones seen in the screenshot below)

Grafana and prometheus are setup in Node A, whereas chia-monitor is installed on both nodes and they are made available to prometheus using this config:

```
scrape_configs:
  - job_name: chia_monitor_node_a
    static_configs:
    - targets: ['127.0.0.1:8000']
  - job_name: chia_monitor_node_b
    static_configs:
    - targets: ['NODE_B_DOMAIN_NAME.COM:8000']
```

So the issue is caused by the fact Node B and its harvesters are behind 2 routers before reaching the internet:

```              
Node B
-------- Network2 - 192.168.2.0
Router2
-------- Network1 - 192.168.1.0
Router1
-------- INTERNET
```

Router1 is set to have Router2 as DMZ, and then port 8000 is forwarded in Router2 toward Node B.

In the dashboard I get 2 entries for harvester B2, one with its own IP address, and one with Router2's IP. and this doesn't happen with the other 2 harvesters.

![image](https://user-images.githubusercontent.com/2863796/126102608-0cec1ec7-fef7-4ea0-9f41-121ede444757.png)

All the metrics that report the harvester host have the same issue. One workaround I found was to change the PromQL query in Grafana to have a filter for that duplicate entry like so: `chia_plot_size{host!="192.168.2.1"}`. but I'm still wondering if it's not messing up other things like notifications (In telegram I have plots changed in 24H at -99 plots...).

**Comment by philippnormann** [comment]
Hmm strange... Do you see the same result when using `chia farm summary`?

**Comment by charnet3d** [comment]
Okeey so it seems chia is detecting that harvester in a weird way:

```
Local Harvester
   208 plots of size: 20.590 TiB
Remote Harvester for IP: 192.168.2.206
   81 plots of size: 8.018 TiB
Remote Harvester for IP: 192.168.2.1
   103 plots of size: 10.196 TiB
```

The machines are set with the IPs 192.168.1.203 for the main node, 192.168.2.205 (the one detected sometimes as 192.168.2.1 same as router IP) and 192.168.2.206 (this one I changed from 192.168.2.8 in the screenshots above)

In the harvesters the config is set like this:

```
harvester:
  # The harvester server (if run) will run on this port
  port: 8448
  farmer_peer:
    host: 192.168.2.203
    port: 8447
```

When I saw that I thought I forgot an earlier setting where I was using a domain name and thus I go through the router, this would have explained it, but it's actually configured as LAN only...

Anyway this doesn't relate to chia-monitor, but more to chia's harvester detection. You can close if you don't see any obvious fix/workaround.

Thanks.
